#version 430

layout(local_size_x = 32, local_size_y = 32) in;

layout(std430, binding = 0) readonly buffer read_buffer {
   float read[];
};

layout(std430, binding = 1) writeonly buffer write_buffer {
   float write[];
};

layout(std430, binding = 2) readonly restrict buffer kernel_buffer {
   float kernel[];
};

layout(std430, binding = 3) writeonly buffer data_buffer {
    uint globalFieldSum;
    uint globalCenterOfMassX;
    uint globalCenterOfMassY;
};

shared uint localSum;
shared uint localCenterOfMassX;
shared uint localCenterOfMassY;

layout(location = 0) uniform uint W;
layout(location = 1) uniform uint H;
layout(location = 2) uniform uint R;
layout(location = 3) uniform float dt;
layout(location = 4) uniform float mu;
layout(location = 5) uniform float sigma;
layout(location = 6) uniform float dx2;
layout(location = 7) uniform uint gn;

float G(const float u) {
    switch(gn) {
        case 0:
            return pow(max(0.0, 1.0 - pow(u - mu, 2.0) / (9.0 * sigma * sigma)), 4.0) * 2.0 - 1.0;
        case 1:
            return exp(-pow(u - mu, 2.0) / (2.0 * sigma * sigma)) * 2.0 - 1.0;
        case 2:
            return abs(u - mu) * 2.0 - 1.0;
    }
}


void main() {
    const uint x = gl_GlobalInvocationID.x;
    const uint y = gl_GlobalInvocationID.y;

    if (x >= W || y >= H) return;


    const uint index = x + y * W;
    const int iR = int(R);
    float Ut = 0.0;

    for (int i = 0; i < iR; i++) 
    for (int j = 0; j < iR; j++) {
        const uint xoff = (x + i) % W;
        const uint yoff = (y + j) % H * W;
        const uint xwrap = (W + x - i) % W;
        const uint ywrap = (H + y - j) % H * W; 
        Ut += uint(i*i + j*j <= iR*iR) * kernel[i * iR + j] * (
                read[yoff + xoff]
            +   read[ywrap + xoff] * float(j != 0)
            +   read[yoff + xwrap] * float(i != 0)
            +   read[ywrap + xwrap] * float(i != 0 && j != 0)
		);
    }
    
    const float state = clamp(read[index] + (dt * G(Ut * dx2)), 0.0, 1.0);
    write[index] = state;

    barrier();

    atomicAdd(localSum, uint(state * float(1e4)));
    atomicAdd(localCenterOfMassX, uint(state * 100.0) * x);
    atomicAdd(localCenterOfMassY, uint(state * 100.0) * y);
    

    barrier();

    if (gl_LocalInvocationIndex == 0) {
        atomicAdd(globalFieldSum, localSum);
        atomicAdd(globalCenterOfMassX, localCenterOfMassX);
        atomicAdd(globalCenterOfMassY, localCenterOfMassY);
    }
}