#version 430


layout(std430, binding = 6) readonly buffer comp_read_buffer {
    vec2 comp_read[];
};

layout(std430, binding = 7) writeonly buffer comp_write_buffer {
    vec2 comp_write[];
};

layout(std430, binding = 8) readonly buffer comp_kernel_buffer {
    vec2 comp_kernel[];
};


uniform int width; // Width of the input texture
uniform int pass;  // Pass level for the FFT (log2 of width)

vec2 cplx_mul(vec2 lhs, vec2 rhs) 
{
    return vec2(lhs.x * rhs.x - lhs.y * rhs.y, lhs.y * rhs.x + lhs.x * rhs.y);
}

uint rev_bits(uint num) 
{ 
    uint count = 31; 
    uint reverse_num = num; 
      
    num >>= 1;  
    while(num != 0) 
    { 
       reverse_num <<= 1;        
       reverse_num |= num & 1; 
       num >>= 1; 
       count--; 
    } 
    reverse_num <<= count; 
    return reverse_num; 
} 

uint index_map(uint threadId, uint currentIteration, uint N)
{
    return ((threadId & (N - (1u << currentIteration))) << 1) | (threadId & ((1u << currentIteration) - 1));
}

uint twiddle_map(uint threadId, uint currentIteration, uint logTwo, uint N)
{
    return (threadId & (N / (1u << (logTwo - currentIteration)) - 1)) * (1u << (logTwo - currentIteration)) >> 1;
}

vec2 twiddle(float q, bool is_inverse, float N)
{
	float theta = float(int(!is_inverse) * 2 - 1) * 2.0 * 3.141592653 * q / N;

	float r = cos(theta);
	float i = sqrt(1.0 - r*r) * float(int(theta < 0.0) * 2 - 1);

	return vec2(r, i);
}

void fft_radix2(int logTwo, int btid, int g_offset, bool is_inverse, float N)
{
    for(int i = 0; i < logTwo; i++)
    {
        for(int j = btid; j < btid + g_offset; j++)
        {
            uint even = index_map(uint(j), uint(i), uint(N));
            uint odd = even + (1u << uint(i));
    
            vec2 evenVal = vec2(real_cache[even], imag_cache[even]);
    
            uint q = twiddle_map(uint(j), uint(i), uint(logTwo), uint(N));

            vec2 e = cplx_mul(twiddle(float(q), is_inverse, N), vec2(real_cache[odd], imag_cache[odd]));
    
            vec2 calculatedEven = evenVal + e;
            vec2 calculatedOdd = evenVal - e;

            real_cache[even] = calculatedEven.x;
            imag_cache[even] = calculatedEven.y;

            real_cache[odd] = calculatedOdd.x;
            imag_cache[odd] = calculatedOdd.y;
		}
        sync();
    }
}